# Autogenerated wrapper script for CVRPSEP_jll for x86_64-w64-mingw32
export libcvrpsep

JLLWrappers.@generate_wrapper_header("CVRPSEP")
JLLWrappers.@declare_library_product(libcvrpsep, "libcvrpsep-0.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcvrpsep,
        "bin\\libcvrpsep-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
